CREATE TABLE DOCENTES(

        ID_DOCENTE INTEGER NOT NULL,
        APELLIDO  VARCHAR(15),
	NOMBRES VARCHAR(15),
        ASIGNATURA VARCHAR(15),
        HORARIO VARCHAR(15),
        PRIMARY KEY (ID_DOCENTE)
);

CREATE TABLE ASIGNATURAS(

	ID_ASIGNATURA INTEGER NOT NULL, 
	ID_DOCENTE INTEGER,
	NOMBRE_ASIGNATURA VARCHAR(15),
	HORARIO VARCHAR(15),
	PRIMARY KEY (ID_ASIGNATURA),
        FOREIGN KEY(ID_DOCENTE)REFERENCES DOCENTES(ID_DOCENTE)
	
);

